### PR TITLE
allow relative or blank projectRoot, for #7

### PR DESCRIPTION
**Pull request by konsumer**
This changes how `projectRoot` works slightly, to support relative or non-set values. It also still supports absolute locations.

### CODE REVIEW

**Comment by konsumer** [comment]
Sorry, looks like my auto-formatter did something to the code in utils.js I will put it back.

**Comment by konsumer** [comment]
I feel like my relative path-resolver is a bit hokey, even though it seems to work. I am pretty sure it breaks on paths like `./cool/neat/../whatever` (with relative dots after first segment) but this seems like an edge-case that can be easily worked around, and I can live with it. I looked around for a stdlib "get absolute path from this relative path and location" function (like node's `path.resolve`) but I couldn't figure it out in the QT JS env.  This would be preferable, so if you know how to do it, we should switch it up.

**Comment by bjorn** [comment]
> I looked around for a stdlib "get absolute path from this relative path and location" function (like node's `path.resolve`) but I couldn't figure it out in the QT JS env. This would be preferable, so if you know how to do it, we should switch it up.

I agree we should add some of these convenience methods to the API. Suggestions like this are welcome on the Tiled repository!

**Comment by konsumer** [comment]
@bjorn I am pretty experienced with nodejs & a few other server-side JS implementations, but it seems like QT is quite a bit different, but I like it! Seems like pretty good ES7 support, from what I tried. Is there a stdlib equiv, that people often import into the QT js environment for doing basic stuff like os/fs/path stuff, or does everyone have to roll it themselves?

**Comment by bjorn** [comment]
@konsumer The JavaScript support in Qt is based on V8, so indeed it tends to be pretty good. However, it only ships with the standard JavaScript functionality which does not have any os/fs/path stuff. So indeed, we'll need to expose our own APIs for this.

There is already `TextFile` and `BinaryFile`, and we'll probably add more API for example for XML files and also stuff like these path operations.

**Comment by konsumer** [comment]
I'm going to go make an issue over there, and I'd be happy to help with anything I can.

**Comment by konsumer** [comment]
I made a PR over [here](https://github.com/bjorn/tiled/pull/2782) that will provide some nice file-utils to JS plugin API. Once that's in, I can update the stuff over here. It should be much smarter about resolving `projectRoot` once it's all setup.

**Pull request merged**
