### PR TITLE
Exporting multiple tilesets from same layer as children of a layer

### PR DESCRIPTION
**Pull request by alextrevisan**
My maps have multiple tilesets in the same layer, the exporter give a warning, so I make it support multiple tilesets.

This other tilesets will be children of the first tilset found.

### CODE REVIEW

**Comment by MikeMnD** [comment]
That's a nice solution.
I've just tested it and it looks very well.
image

**Comment by bjorn** [comment]
Don't forget to adjust the `README.md`. :-)

**Comment by MikeMnD** [comment]
Yeah, I did it. It was a one-sentence I think.

**Comment by bjorn** [comment]
@MikeMnD I still read "Each Layer should use only tiles from one tileset" in there.

**Comment by MikeMnD** [comment]
Dunno where I looked yesterday. Now this line is removed since the last one explains what will happen.

**Pull request merged**
