### PR TITLE
Change to column number calculation

### PR DESCRIPTION
**Pull request by agmcleod**
Fixes: https://github.com/MikeMnD/tiled-to-godot-export/issues/17

### CODE REVIEW

**Comment by bjorn** [comment]
Would the version from the tile map export also work? That one matches exactly the calculation done by Tiled:

https://github.com/MikeMnD/tiled-to-godot-export/blob/3ef90d1e4b3204fcfefa6de0c140595174e12319/export_to_godot_tilemap.js#L332-L340

**Comment by agmcleod** [comment]
@bjorn ah good call! I didn't look much at the tilemap export. I'll refactor so both can use a shared function.

**Comment by agmcleod** [comment]
Updated, and tested with my level, seems to work well :)

**Comment by MikeMnD** [comment]
Looks ok to me too even thou can't test it at the moment.
Merge accepted ;)

**Pull request merged**
